FROM vaderspb/arcadium-builder as builder

FROM eclipse-temurin:17-jdk-jammy

WORKDIR /opt/arkadium
COPY --from=builder /opt/arkadium/arcadium-transport/target/arcadium-transport-*.jar arcadium-transport.jar

ENTRYPOINT ["java", "-jar", "arcadium-transport.jar"]
