FROM vaderspb/arcadium-builder as builder

FROM eclipse-temurin:17-jdk-jammy

WORKDIR /opt/arkadium
COPY --from=builder /opt/arkadium/arcadium-api-server/target/arcadium-api-server-*.jar arcadium-api-server.jar

ENTRYPOINT ["java", "-jar", "arcadium-api-server.jar"]
