FROM vaderspb/arcadium-builder as builder

FROM eclipse-temurin:17-jdk-jammy

WORKDIR /opt/arkadium
COPY --from=builder /opt/arkadium/arcadium-worker/arcadium-nes-worker/target/arcadium-nes-worker-*.jar ./
COPY --from=builder /opt/arkadium/arcadium-worker/arcadium-nes-worker/target/lib/*.jar ./

ENTRYPOINT ["java", "-cp", "*", "com.vaderspb.worker.nes.Application"]
