apiVersion: batch/v1
kind: Job
metadata:
  name: arcadium-worker-{{workerId}}
spec:
  backoffLimit: 10
  template:
    metadata:
      labels:
        app: arcadium-worker
    spec:
      hostname: {{workerId}}
      subdomain: arcadium-worker
      containers:
        - name: app
          image: vaderspb/arcadium-worker:0.0.1v17
          args:
            - -XX:InitialRAMPercentage=80
            - -XX:MaxRAMPercentage=80
          env:
            - name: ROM_FILE
              value: /opt/arkadium/Battletoads.nes
            - name: INACTIVITY_DURATION
              value: PT5M
          ports:
            - name: http2
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 1000m
              memory: 2048Mi
            requests:
              cpu: 1000m
              memory: 2048Mi
      restartPolicy: Never
