apiVersion: batch/v1
kind: Job
metadata:
  name: arcadium-worker
spec:
  backoffLimit: 100
  template:
    metadata:
      labels:
        app: arcadium-worker
    spec:
      hostname: job1
      subdomain: arcadium-worker
      containers:
        - name: app
          image: vaderspb/arcadium-worker:0.0.1v4
          args:
            - -XX:InitialRAMPercentage=80
            - -XX:MaxRAMPercentage=80
          env:
            - name: ROM_FILE
              value: /opt/arkadium/Battletoads.nes
            - name: INACTIVITY_DURATION
              value: P1D
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 1000m
              memory: 2048Mi
            requests:
              cpu: 1000m
              memory: 2048Mi
      restartPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: arcadium-worker
spec:
  clusterIP: None
  ports:
    - port: 8080
  selector:
    app: arcadium-worker
