apiVersion: batch/v1
kind: Job
metadata:
  name: arcadium-worker-{{workerId}}
spec:
  backoffLimit: 10
  template:
    metadata:
      labels:
        app: arcadium-worker
    spec:
      hostname: {{ workerId }}
      subdomain: arcadium-worker
      volumes:
        - name: nes-data
          emptyDir: { }
      initContainers:
        - name: nes-loader
          image: curlimages/curl:8.5.0
          command:
            - curl
            - -o
            - /var/nes/game.nes
            - http://arcadium-storage-service:8080/nes/Battletoads.nes
          volumeMounts:
            - mountPath: /var/nes
              name: nes-data
          resources:
            limits:
              cpu: 250m
              memory: 128Mi
            requests:
              cpu: 250m
              memory: 128Mi
      containers:
        - name: app
          image: {{ workerConfig.image }}
          args:
            - -XX:InitialRAMPercentage=80
            - -XX:MaxRAMPercentage=80
          env:
            - name: ROM_FILE
              value: /var/nes/game.nes
            - name: INACTIVITY_DURATION
              value: PT10M
          ports:
            - name: http2
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /var/nes
              name: nes-data
          resources:
            limits:
              cpu: {{ workerConfig.resources.limits.cpu }}
              memory: {{ workerConfig.resources.limits.memory }}
            requests:
              cpu: {{ workerConfig.resources.requests.cpu }}
              memory: {{ workerConfig.resources.requests.memory }}
      restartPolicy: Never
